options:
  - text: "ะะฐะทะดะตะป ะฝะพะผะตั ะพะดะธะฝ"
    options:
      - text: "ะะพะด-ัะฐะทะดะตะป ะฝะพะผะตั ะพะดะธ ๐ฉ๐ฟโ๐ฆฑ"
        hint: |
          ะะพะดัะบะฐะทะบะฐ, ะบะพัะพัะฐั 
          ะผะฝะพะณะพัััะพัะฝะฐั 
          ะะฝะฐ ะผะฝะพะณะพััะพััะฐั ะฟะพัะพะผั ััะพ ัะฐะนะฟ 
          ัะฐะนะฟ ััะพ ััะพ ๐ค
        chat_id: 1231920
  - text: "โค ะะฐะทะดะตะป ะฝะพะผะตั ะดะฒะฐ"
    hint: "๐ ะฅะพัะตัั ัะฐะน ?"
    chat_id: 123912031